#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += gt9772af.o
